# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 200

checkpoint:
  save_interval: 5
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: data2vec_audio_text_finetuning
  data: ???
  max_sample_size: 320000
  min_sample_size: 32000
  normalize: true
  labels: bpe

dataset:
  num_workers: 6
  max_tokens: 3800000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true
  train_subset: train
  valid_subset: dev_other

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 8

criterion: model_for_data2vec

optimization:
  max_update: 400000
  clip_norm: 5
  lr: [0.0002]
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

# lr_scheduler:
#   _name: tri_stage
#   phase_ratio: [0.1, 0.4, 0.5]
#   final_lr_scale: 0.05

lr_scheduler:
  _name: cosine

model:
  _name: data2vec_bimodal
  ema_pretraining: true
  w2v_ctc_path: ???
  roberta_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0
  average_top_k_layers: 4
  layer_norm_target_layer: true
  ema_decay: 0.999
  ema_end_decay: 0.9999
  ema_anneal_end_step: 300000
  loss_beta: 4
  loss_scale: 1