common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: ???

checkpoint:
  save_dir: ???
  save_interval_updates: 10000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_finetuning
  eval_bleu: true
  eval_bleu_detok: space
  eval_bleu_print_samples: true
  autoregressive : true
  data: ???
  normalize: false
  labels: ltr

dataset:
  num_workers: 8
  max_tokens: 1280000
  skip_invalid_size_inputs_valid_test: true
  valid_subset: valid

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: label_smoothed_cross_entropy
  label_smoothing: 0.1
  report_accuracy: true

optimization:
  max_update: 160000
  lr: [0.00003]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_seq2seq
  w2v_path: ???
  apply_mask: false # true
  mask_prob: 0.5
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000

