# @package hydra.sweeper
_target_: hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper
max_batch_size: null
ax_config:
  max_trials: 128
  early_stop:
    minimize: true
    max_epochs_without_improvement: 32
    epsilon: 1.0e-05
  experiment:
    name: ${dataset.gen_subset}
    objective_name: wer
    minimize: true
    parameter_constraints: null
    outcome_constraints: null
    status_quo: null
  client:
    verbose_logging: false
    random_seed: null
  params:
    decoding.silweight:
      type: range
      value_type: float
      bounds: [-5.0, 5.0]
    decoding.beamthreshold:
      type: choice
      value_type: float
      values: [5.0, 10.0, 15.0, 20.0, 25.0, 50.0, 100.0]

# [WARNING 12-22 01:55:52] ax.core.parameter: `sort_values` is not specified for `ChoiceParameter` 
#"decoding.beamthreshold". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.

# ValueError: Unexpected keys {'sort_values'} in parameter representation.Exhaustive set of expected keys: 
# {'type', 'values', 'log_scale', 'value', 'value_type', 'target_value', 'is_fidelity', 'name', 'is_ordered', 'digits', 'bounds', 'is_task'}.


# banana.y:
#  type: range
#  bounds: [-5, 10.1]

# name - Name of the parameter. It is of type string.
# type - Type of the parameter. It can take the following values: range, fixed, or choice.
# bounds - Required only for the range parameters. It should be a list of two values, with the lower bound first.
# values - Required only for the choice parameters. It should be a list of values.
# value - Required only for the fixed parameters. It should be a single value.

