# @package hydra.sweeper
_target_: hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper
max_batch_size: null
ax_config:
  max_trials: 128
  early_stop:
    minimize: true
    max_epochs_without_improvement: 32
    epsilon: 1.0e-05
  experiment:
    name: ${dataset.gen_subset}
    objective_name: wer
    minimize: true
    parameter_constraints: null
    outcome_constraints: null
    status_quo: null
  client:
    verbose_logging: false
    random_seed: null
  params:
    decoding.rescoringweight:
      type: range
      bounds: [0.0, 5.0]
    decoding.rescoringwordlenweight:
      type: range
      bounds: [-5.0, 5.0]



# decoding.rescoringweight:
#   type: choice
#   value_type: float
#   values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7,5, 8.0, 8.5, 9.0, 9.5, 10.0]
# decoding.rescoringwordlenweight:
#   type: choice
#   value_type: float
#   values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, , 1.4, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
